[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  # Remove or comment out the following line:
  # NODE_OPTIONS = "--openssl-legacy-provider"
